## Target Guided Ordinal Encoding 
It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [1]:
import pandas as pd

# create a sample dataframe with a categorical variable and a target variable
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [2]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [3]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [4]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [5]:
df['city_encoded']=df['city'].map(mean_price)

In [6]:
df[['price','city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0

In [7]:
import seaborn as sns
df = sns.load_dataset('tips')

In [8]:
df.shape

(244, 7)

In [9]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [11]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [13]:
df.sex.value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [16]:
from sklearn.preprocessing import OneHotEncoder
encode = OneHotEncoder()
encoder = encode.fit_transform(df[['sex']]).toarray()

In [26]:
df_encode_sex = pd.DataFrame(encoder, columns=encode.get_feature_names_out())

In [27]:
df_encode_sex

     sex_Female  sex_Male
0           1.0       0.0
1           0.0       1.0
2           0.0       1.0
3           0.0       1.0
4           1.0       0.0
..          ...       ...
239         0.0       1.0
240         1.0       0.0
241         0.0       1.0
242         0.0       1.0
243         1.0       0.0

[244 rows x 2 columns]

In [19]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [20]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [23]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['lable_encode_day'] = label_encoder.fit_transform(df['day'])

In [25]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [28]:
encoder = encode.fit_transform(df[['time']]).toarray()
df_encode_time = pd.DataFrame(encoder, columns=encode.get_feature_names_out())

In [29]:
encoder = encode.fit_transform(df[['smoker']]).toarray()
df_encode_smoker = pd.DataFrame(encoder, columns=encode.get_feature_names_out())

In [33]:
featured_df = pd.concat([df, df_encode_sex, df_encode_time, df_encode_smoker], axis=1).select_dtypes(include='number')

In [34]:
featured_df.head()

,total_bill,tip,size,lable_encode_day,sex_Female,sex_Male,time_Dinner,time_Lunch,smoker_No,smoker_Yes
0,16.99,1.01,2,2,1.0,0.0,1.0,0.0,1.0,0.0
1,10.34,1.66,3,2,0.0,1.0,1.0,0.0,1.0,0.0
2,21.01,3.50,3,2,0.0,1.0,1.0,0.0,1.0,0.0
3,23.68,3.31,2,2,0.0,1.0,1.0,0.0,1.0,0.0
4,24.59,3.61,4,2,1.0,0.0,1.0,0.0,1.0,0.0